// Generated automatically using to-firmware-include.mjs

#define MSG_APP_ENVIRONMENT_ID 603
#define MSG_APP_ENVIRONMENT_BUS 1
#define MSG_DI_VEHICLEESTIMATES_ID 615
#define MSG_DI_VEHICLEESTIMATES_BUS 0
#define MSG_VCLEFT_LIFTGATESTATUS_ID 322
#define MSG_VCLEFT_LIFTGATESTATUS_BUS 0
#define MSG_VCSEC_TPMSDATA_ID 537
#define MSG_VCSEC_TPMSDATA_BUS 1
#define MSG_VCSEC_TPMSCONNECTIONDATA_ID 1066
#define MSG_VCSEC_TPMSCONNECTIONDATA_BUS 0
#define MSG_VCLEFT_LIGHTSTATUS_ID 994
#define MSG_VCLEFT_LIGHTSTATUS_BUS 0
#define MSG_VCFRONT_LOGGING10HZ2_ID 513
#define MSG_VCFRONT_LOGGING10HZ2_BUS 0
#define MSG_UI_TRIPPLANNING_ID 130
#define MSG_UI_TRIPPLANNING_BUS 0
#define MSG_UI_TRIPPLANNING2_ID 139
#define MSG_UI_TRIPPLANNING2_BUS 0
#define MSG_CMPD_STATE_ID 680
#define MSG_CMPD_STATE_BUS 0
#define MSG_VIN_INFO_ID 1029
#define MSG_VIN_INFO_BUS 0
#define MSG_BMS_BRICKVOLTAGES_ID 1025
#define MSG_BMS_BRICKVOLTAGES_BUS 0
#define MSG_UTC_SYSTEMTIME_ID 792
#define MSG_UTC_SYSTEMTIME_BUS 0
#define MSG_UTC_UNIXTIME_ID 1320
#define MSG_UTC_UNIXTIME_BUS 0
#define MSG_APB_STATUS_ID 600
#define MSG_APB_STATUS_BUS 1
#define MSG_APP_BOARDTEMPERATURES_ID 1020
#define MSG_APP_BOARDTEMPERATURES_BUS 1
#define MSG_APP_CAMCALIBRATIONSTATUS_ID 1012
#define MSG_APP_CAMCALIBRATIONSTATUS_BUS 1
#define MSG_APP_CAMERALUX_ID 1018
#define MSG_APP_CAMERALUX_BUS 1
#define MSG_APP_CAMERASTATUS_ID 1040
#define MSG_APP_CAMERASTATUS_BUS 1
#define MSG_APP_INFO_ID 1353
#define MSG_APP_INFO_BUS 1
#define MSG_APP_STATUS_ID 601
#define MSG_APP_STATUS_BUS 1
#define MSG_APP_WARNINGMATRIX0_ID 809
#define MSG_APP_WARNINGMATRIX0_BUS 1
#define MSG_APP_WARNINGMATRIX1_ID 873
#define MSG_APP_WARNINGMATRIX1_BUS 1
#define MSG_APP_WARNINGMATRIX2_ID 1065
#define MSG_APP_WARNINGMATRIX2_BUS 1
#define MSG_APP_WARNINGMATRIX3_ID 1081
#define MSG_APP_WARNINGMATRIX3_BUS 1
#define MSG_APP_WARNINGMATRIX4_ID 1097
#define MSG_APP_WARNINGMATRIX4_BUS 1
#define MSG_APS_EACMONITOR_ID 637
#define MSG_APS_EACMONITOR_BUS 0
#define MSG_APS_STATUS_ID 970
#define MSG_APS_STATUS_BUS 1
#define MSG_APS_WARNINGMATRIX0_ID 811
#define MSG_APS_WARNINGMATRIX0_BUS 1
#define MSG_APS_WARNINGMATRIX1_ID 876
#define MSG_APS_WARNINGMATRIX1_BUS 1
#define MSG_APS_WARNINGMATRIX2_ID 1113
#define MSG_APS_WARNINGMATRIX2_BUS 1
#define MSG_APS_WARNINGMATRIX3_ID 848
#define MSG_APS_WARNINGMATRIX3_BUS 1
#define MSG_BMS_ALERTMATRIX_ID 800
#define MSG_BMS_ALERTMATRIX_BUS 0
#define MSG_BMS_BMBMINMAX_ID 818
#define MSG_BMS_BMBMINMAX_BUS 0
#define MSG_BMS_CHARGERREQUEST_ID 690
#define MSG_BMS_CHARGERREQUEST_BUS 0
#define MSG_BMS_DRIVELIMITS_ID 722
#define MSG_BMS_DRIVELIMITS_BUS 0
#define MSG_BMS_ENERGYSTATUS_ID 850
#define MSG_BMS_ENERGYSTATUS_BUS 0
#define MSG_BMS_HVBUSSTATUS_ID 306
#define MSG_BMS_HVBUSSTATUS_BUS 0
#define MSG_BMS_INFO_ID 768
#define MSG_BMS_INFO_BUS 0
#define MSG_BMS_KWHCOUNTER_ID 978
#define MSG_BMS_KWHCOUNTER_BUS 0
#define MSG_BMS_KWHCOUNTERSMULTIPLEXED_ID 1010
#define MSG_BMS_KWHCOUNTERSMULTIPLEXED_BUS 0
#define MSG_BMS_POWERAVAILABLE_ID 594
#define MSG_BMS_POWERAVAILABLE_BUS 0
#define MSG_BMS_SOCSTATUS_ID 658
#define MSG_BMS_SOCSTATUS_BUS 0
#define MSG_UI_RANGESOC_ID 826
#define MSG_UI_RANGESOC_BUS 0
#define MSG_BMS_STATUS_ID 530
#define MSG_BMS_STATUS_BUS 0
#define MSG_BMS_THERMALSTATUS_ID 786
#define MSG_BMS_THERMALSTATUS_BUS 0
#define MSG_BMS_UDSRESPONSE_ID 1554
#define MSG_BMS_UDSRESPONSE_BUS 0
#define MSG_BMS_VEHNM_ID 754
#define MSG_BMS_VEHNM_BUS 0
#define MSG_CC_ALERTMATRIX1_ID 1132
#define MSG_CC_ALERTMATRIX1_BUS 0
#define MSG_CC_CHGSTATUS_ID 796
#define MSG_CC_CHGSTATUS_BUS 0
#define MSG_CC_CHGSTATUS2_ID 797
#define MSG_CC_CHGSTATUS2_BUS 0
#define MSG_CC_LOGDATA_ID 812
#define MSG_CC_LOGDATA_BUS 0
#define MSG_CMP_INFO_ID 867
#define MSG_CMP_INFO_BUS 0
#define MSG_CMP_UDSRESPONSE_ID 1555
#define MSG_CMP_UDSRESPONSE_BUS 0
#define MSG_CP_ALERTMATRIX_ID 798
#define MSG_CP_ALERTMATRIX_BUS 0
#define MSG_CP_CHARGESTATUS_ID 317
#define MSG_CP_CHARGESTATUS_BUS 0
#define MSG_CP_EVSESTATUS_ID 541
#define MSG_CP_EVSESTATUS_BUS 0
#define MSG_CP_INFO_ID 1342
#define MSG_CP_INFO_BUS 0
#define MSG_CP_SENSORDATA_ID 1885
#define MSG_CP_SENSORDATA_BUS 0
#define MSG_CP_STATUS_ID 605
#define MSG_CP_STATUS_BUS 0
#define MSG_CP_DCCHARGESTATUS_ID 669
#define MSG_CP_DCCHARGESTATUS_BUS 0
#define MSG_CP_UDSRESPONSE_ID 1566
#define MSG_CP_UDSRESPONSE_BUS 0
#define MSG_DAS_AUTOPILOTDEBUG_ID 583
#define MSG_DAS_AUTOPILOTDEBUG_BUS 0
#define MSG_DAS_BODYCONTROLS_ID 1001
#define MSG_DAS_BODYCONTROLS_BUS 0
#define MSG_DAS_CONTROL_ID 697
#define MSG_DAS_CONTROL_BUS 1
#define MSG_DAS_INFO_ID 1337
#define MSG_DAS_INFO_BUS 1
#define MSG_DAS_LANES_ID 569
#define MSG_DAS_LANES_BUS 1
#define MSG_DAS_OBJECT_ID 777
#define MSG_DAS_OBJECT_BUS 1
#define MSG_DAS_STATUS_ID 921
#define MSG_DAS_STATUS_BUS 1
#define MSG_DAS_STATUS2_ID 905
#define MSG_DAS_STATUS2_BUS 1
#define MSG_DAS_TELEMETRY_ID 937
#define MSG_DAS_TELEMETRY_BUS 0
#define MSG_DAS_TELEMETRYEVENT_ID 986
#define MSG_DAS_TELEMETRYEVENT_BUS 0
#define MSG_DAS_TELEMETRYFURNITURE_ID 945
#define MSG_DAS_TELEMETRYFURNITURE_BUS 0
#define MSG_DAS_TELEMETRYPERIODIC_ID 890
#define MSG_DAS_TELEMETRYPERIODIC_BUS 0
#define MSG_DAS_TELEMETRYRADAR_ID 1548
#define MSG_DAS_TELEMETRYRADAR_BUS 0
#define MSG_DAS_UDSRESPONSE_ID 1625
#define MSG_DAS_UDSRESPONSE_BUS 0
#define MSG_DAS_VISUALDEBUG_ID 586
#define MSG_DAS_VISUALDEBUG_BUS 1
#define MSG_DAS_WARNINGMATRIX0_ID 810
#define MSG_DAS_WARNINGMATRIX0_BUS 0
#define MSG_DAS_WARNINGMATRIX1_ID 874
#define MSG_DAS_WARNINGMATRIX1_BUS 0
#define MSG_DAS_WARNINGMATRIX2_ID 841
#define MSG_DAS_WARNINGMATRIX2_BUS 0
#define MSG_DAS_WARNINGMATRIX3_ID 1082
#define MSG_DAS_WARNINGMATRIX3_BUS 0
#define MSG_DIS_ALERTMATRIX1_ID 933
#define MSG_DIS_ALERTMATRIX1_BUS 0
#define MSG_DIS_ALERTMATRIX2_ID 949
#define MSG_DIS_ALERTMATRIX2_BUS 0
#define MSG_DIS_ALERTMATRIX3_ID 965
#define MSG_DIS_ALERTMATRIX3_BUS 0
#define MSG_DIS_ALERTMATRIX4_ID 997
#define MSG_DIS_ALERTMATRIX4_BUS 0
#define MSG_DIS_CAPABILITY2_ID 392
#define MSG_DIS_CAPABILITY2_BUS 0
#define MSG_DIS_INFO_ID 821
#define MSG_DIS_INFO_BUS 0
#define MSG_DIS_POWER_ID 741
#define MSG_DIS_POWER_BUS 0
#define MSG_DIS_FRONTTORQUE_ID 390
#define MSG_DIS_FRONTTORQUE_BUS 0
#define MSG_DIS_TORQUE_ID 472
#define MSG_DIS_TORQUE_BUS 0
#define MSG_DIS_UDSRESPONSE_ID 1557
#define MSG_DIS_UDSRESPONSE_BUS 0
#define MSG_DI_ALERTMATRIX1_ID 854
#define MSG_DI_ALERTMATRIX1_BUS 0
#define MSG_DI_ALERTMATRIX2_ID 855
#define MSG_DI_ALERTMATRIX2_BUS 0
#define MSG_DI_ALERTMATRIX3_ID 858
#define MSG_DI_ALERTMATRIX3_BUS 0
#define MSG_DI_ALERTMATRIX4_ID 859
#define MSG_DI_ALERTMATRIX4_BUS 0
#define MSG_DI_CHASSISCONTROLSTATUS_ID 694
#define MSG_DI_CHASSISCONTROLSTATUS_BUS 0
#define MSG_DI_DEBUG_ID 2005
#define MSG_DI_DEBUG_BUS 0
#define MSG_DI_DYNO_ID 1880
#define MSG_DI_DYNO_BUS 0
#define MSG_DI_ESTIMATEDBRAKETEMP_ID 1022
#define MSG_DI_ESTIMATEDBRAKETEMP_BUS 0
#define MSG_DI_INFO_ID 1622
#define MSG_DI_INFO_BUS 0
#define MSG_DI_LOCSTATUS_ID 646
#define MSG_DI_LOCSTATUS_BUS 0
#define MSG_DI_MAXRATEDPOWER_ID 822
#define MSG_DI_MAXRATEDPOWER_BUS 0
#define MSG_DI_ODOMETERSTATUS_ID 950
#define MSG_DI_ODOMETERSTATUS_BUS 0
#define MSG_DI_OILPUMP_ID 917
#define MSG_DI_OILPUMP_BUS 0
#define MSG_DI_FRONTOILPUMP_ID 918
#define MSG_DI_FRONTOILPUMP_BUS 0
#define MSG_DI_POWER_ID 614
#define MSG_DI_POWER_BUS 0
#define MSG_DI_HVBUSSTATUS_ID 294
#define MSG_DI_HVBUSSTATUS_BUS 0
#define MSG_DI_FRONTHVBUSSTATUS_ID 421
#define MSG_DI_FRONTHVBUSSTATUS_BUS 0
#define MSG_DI_SPEED_ID 599
#define MSG_DI_SPEED_BUS 0
#define MSG_DI_SYSTEMPOWER_ID 616
#define MSG_DI_SYSTEMPOWER_BUS 0
#define MSG_DI_SYSTEMSTATUS_ID 280
#define MSG_DI_SYSTEMSTATUS_BUS 0
#define MSG_DI_FRONTINVERTERTEMPERATURE_ID 886
#define MSG_DI_FRONTINVERTERTEMPERATURE_BUS 0
#define MSG_DI_TEMPERATURE_ID 789
#define MSG_DI_TEMPERATURE_BUS 0
#define MSG_DI_FRONTTEMPERATURE_ID 886
#define MSG_DI_FRONTTEMPERATURE_BUS 0
#define MSG_DI_FRONTTHERMALCONTROL_ID 1367
#define MSG_DI_FRONTTHERMALCONTROL_BUS 0
#define MSG_DI_THERMALCONTROL_ID 1495
#define MSG_DI_THERMALCONTROL_BUS 0
#define MSG_DI_TORQUE_ID 264
#define MSG_DI_TORQUE_BUS 0
#define MSG_DI_UDSRESPONSE_ID 1558
#define MSG_DI_UDSRESPONSE_BUS 0
#define MSG_EPAS3P_ALERTMATRIX_ID 914
#define MSG_EPAS3P_ALERTMATRIX_BUS 0
#define MSG_EPAS3P_INFO_ID 817
#define MSG_EPAS3P_INFO_BUS 0
#define MSG_EPAS3P_SYSSTATUS_ID 883
#define MSG_EPAS3P_SYSSTATUS_BUS 0
#define MSG_EPAS3P_UDSRESPONSECH_ID 1592
#define MSG_EPAS3P_UDSRESPONSECH_BUS 0
#define MSG_EPAS3S_ALERTMATRIX_ID 913
#define MSG_EPAS3S_ALERTMATRIX_BUS 1
#define MSG_EPAS3S_INFO_ID 785
#define MSG_EPAS3S_INFO_BUS 1
#define MSG_EPAS3S_SYSSTATUS_ID 882
#define MSG_EPAS3S_SYSSTATUS_BUS 0
#define MSG_EPAS3S_UDSRESPONSE_ID 1848
#define MSG_EPAS3S_UDSRESPONSE_BUS 0
#define MSG_EPBL_ALERTMATRIX_ID 968
#define MSG_EPBL_ALERTMATRIX_BUS 0
#define MSG_EPBL_INFO_ID 1992
#define MSG_EPBL_INFO_BUS 0
#define MSG_EPBL_INTERNALSTATUS_ID 648
#define MSG_EPBL_INTERNALSTATUS_BUS 0
#define MSG_EPBL_STATUS_ID 681
#define MSG_EPBL_STATUS_BUS 0
#define MSG_EPBL_UDSRESPONSE_ID 1573
#define MSG_EPBL_UDSRESPONSE_BUS 0
#define MSG_EPBR_ALERTMATRIX_ID 1000
#define MSG_EPBR_ALERTMATRIX_BUS 0
#define MSG_EPBR_INFO_ID 2024
#define MSG_EPBR_INFO_BUS 0
#define MSG_EPBR_INTERNALSTATUS_ID 552
#define MSG_EPBR_INTERNALSTATUS_BUS 0
#define MSG_EPBR_STATUS_ID 744
#define MSG_EPBR_STATUS_BUS 0
#define MSG_EPBR_UDSRESPONSE_ID 1575
#define MSG_EPBR_UDSRESPONSE_BUS 0
#define MSG_ESP_ALERTMATRIX_ID 981
#define MSG_ESP_ALERTMATRIX_BUS 1
#define MSG_ESP_INFO_ID 808
#define MSG_ESP_INFO_BUS 0
#define MSG_ESP_STATUS_ID 325
#define MSG_ESP_STATUS_BUS 1
#define MSG_ESP_WHEELROTATION_ID 341
#define MSG_ESP_WHEELROTATION_BUS 1
#define MSG_ESP_WHEELSPEED_ID 373
#define MSG_ESP_WHEELSPEED_BUS 1
#define MSG_ESP_BRAKETORQUE_ID 389
#define MSG_ESP_BRAKETORQUE_BUS 1
#define MSG_ESP_UDSRESPONSE_ID 1621
#define MSG_ESP_UDSRESPONSE_BUS 0
#define MSG_FC_ALERTMATRIX1_ID 805
#define MSG_FC_ALERTMATRIX1_BUS 0
#define MSG_FC_ALERTMATRIX2_ID 831
#define MSG_FC_ALERTMATRIX2_BUS 0
#define MSG_FC_ALERTMATRIX3_ID 895
#define MSG_FC_ALERTMATRIX3_BUS 0
#define MSG_FC_ALERTMATRIX4_ID 927
#define MSG_FC_ALERTMATRIX4_BUS 0
#define MSG_FC_ALERTMATRIX5_ID 958
#define MSG_FC_ALERTMATRIX5_BUS 0
#define MSG_FC_ALERTMATRIX6_ID 990
#define MSG_FC_ALERTMATRIX6_BUS 0
#define MSG_FC_IDENTIFIER_ID 1303
#define MSG_FC_IDENTIFIER_BUS 0
#define MSG_FC_INFO_ID 1310
#define MSG_FC_INFO_BUS 0
#define MSG_FC_LIMITS_ID 580
#define MSG_FC_LIMITS_BUS 0
#define MSG_FC_MAXLIMITS_ID 1345
#define MSG_FC_MAXLIMITS_BUS 0
#define MSG_FC_STATUS_ID 532
#define MSG_FC_STATUS_BUS 0
#define MSG_FC_STATUS2_ID 533
#define MSG_FC_STATUS2_BUS 0
#define MSG_FC_STATUS3_ID 535
#define MSG_FC_STATUS3_BUS 0
#define MSG_GTW_ECALL_ID 888
#define MSG_GTW_ECALL_BUS 0
#define MSG_GTW_ADC1_ID 274
#define MSG_GTW_ADC1_BUS 0
#define MSG_GTW_ADC2_ID 275
#define MSG_GTW_ADC2_BUS 0
#define MSG_GTW_ADC3_ID 276
#define MSG_GTW_ADC3_BUS 0
#define MSG_GTW_ALERTMATRIX_ID 62
#define MSG_GTW_ALERTMATRIX_BUS 0
#define MSG_GTW_BUSLOADINFO_ID 281
#define MSG_GTW_BUSLOADINFO_BUS 0
#define MSG_GTW_CANSTATUS_ID 904
#define MSG_GTW_CANSTATUS_BUS 0
#define MSG_GTW_CARCONFIG_ID 2047
#define MSG_GTW_CARCONFIG_BUS 0
#define MSG_GTW_DISKIOERR_ID 1323
#define MSG_GTW_DISKIOERR_BUS 0
#define MSG_GTW_VEHNM_ID 1080
#define MSG_GTW_VEHNM_BUS 0
#define MSG_GTW_FACTORYECUPRESENT_ID 1376
#define MSG_GTW_FACTORYECUPRESENT_BUS 0
#define MSG_GTW_HRL_ID 2033
#define MSG_GTW_HRL_BUS 0
#define MSG_GTW_INFO_ID 60
#define MSG_GTW_INFO_BUS 0
#define MSG_GTW_STATUS_ID 840
#define MSG_GTW_STATUS_BUS 0
#define MSG_GTW_UPDATESTATUS_ID 872
#define MSG_GTW_UPDATESTATUS_BUS 0
#define MSG_GTW_VEHNM_ID 1112
#define MSG_GTW_VEHNM_BUS 0
#define MSG_HVP_ALERTMATRIX1_ID 938
#define MSG_HVP_ALERTMATRIX1_BUS 0
#define MSG_HVP_CONTACTORSTATE_ID 522
#define MSG_HVP_CONTACTORSTATE_BUS 0
#define MSG_HVP_DEBUGMESSAGE_ID 1962
#define MSG_HVP_DEBUGMESSAGE_BUS 0
#define MSG_HVP_INFO_ID 784
#define MSG_HVP_INFO_BUS 0
#define MSG_HVP_UDSRESPONSE_ID 1553
#define MSG_HVP_UDSRESPONSE_BUS 0
#define MSG_HVP_VEHICLEDBG_ID 1898
#define MSG_HVP_VEHICLEDBG_BUS 0
#define MSG_IBST_ALERTMATRIX_ID 861
#define MSG_IBST_ALERTMATRIX_BUS 1
#define MSG_IBST_INFO_ID 813
#define MSG_IBST_INFO_BUS 1
#define MSG_IBST_STATUS_ID 925
#define MSG_IBST_STATUS_BUS 1
#define MSG_IBST_UDSRESPONSE_ID 1629
#define MSG_IBST_UDSRESPONSE_BUS 0
#define MSG_OCS1P_STATUS_ID 771
#define MSG_OCS1P_STATUS_BUS 0
#define MSG_OCS1P_UDSRESPONSE_ID 1619
#define MSG_OCS1P_UDSRESPONSE_BUS 0
#define MSG_ODIN_ISOTPPIPEVCSEC_ID 1152
#define MSG_ODIN_ISOTPPIPEVCSEC_BUS 0
#define MSG_PARK_INFO_ID 806
#define MSG_PARK_INFO_BUS 1
#define MSG_PARK_PASFRONTMIDDLE_ID 846
#define MSG_PARK_PASFRONTMIDDLE_BUS 1
#define MSG_PARK_PASREARMIDDLE_ID 862
#define MSG_PARK_PASREARMIDDLE_BUS 1
#define MSG_PARK_PASSIDES_ID 926
#define MSG_PARK_PASSIDES_BUS 1
#define MSG_PARK_PSCENVSLOT_ID 606
#define MSG_PARK_PSCENVSLOT_BUS 1
#define MSG_PARK_PSCSTATUS_ID 542
#define MSG_PARK_PSCSTATUS_BUS 0
#define MSG_PARK_PSCVEHSLOT_ID 590
#define MSG_PARK_PSCVEHSLOT_BUS 1
#define MSG_PARK_SDIFRONT_ID 526
#define MSG_PARK_SDIFRONT_BUS 1
#define MSG_PARK_SDIREAR_ID 558
#define MSG_PARK_SDIREAR_BUS 1
#define MSG_PARK_SENSORSTATUSFRONT_ID 814
#define MSG_PARK_SENSORSTATUSFRONT_BUS 1
#define MSG_PARK_SENSORSTATUSREAR_ID 830
#define MSG_PARK_SENSORSTATUSREAR_BUS 1
#define MSG_PARK_STATUS2_ID 782
#define MSG_PARK_STATUS2_BUS 1
#define MSG_PARK_UDSRESPONSE_ID 1630
#define MSG_PARK_UDSRESPONSE_BUS 0
#define MSG_PARK_WARNINGMATRIX_ID 894
#define MSG_PARK_WARNINGMATRIX_BUS 1
#define MSG_PCS_ALERTMATRIX_ID 932
#define MSG_PCS_ALERTMATRIX_BUS 0
#define MSG_PCS_CHGLINESTATUS_ID 612
#define MSG_PCS_CHGLINESTATUS_BUS 0
#define MSG_PCS_CHGSTATUS_ID 516
#define MSG_PCS_CHGSTATUS_BUS 0
#define MSG_PCS_DCDCBUSSTATUS_ID 692
#define MSG_PCS_DCDCBUSSTATUS_BUS 0
#define MSG_PCS_DCDCSTATUS_ID 548
#define MSG_PCS_DCDCSTATUS_BUS 0
#define MSG_PCS_INFO_ID 964
#define MSG_PCS_INFO_BUS 0
#define MSG_PCS_LOGGING_ID 708
#define MSG_PCS_LOGGING_BUS 0
#define MSG_PCS_THERMALSTATUS_ID 676
#define MSG_PCS_THERMALSTATUS_BUS 0
#define MSG_PCS_UDSRESPONSE_ID 1577
#define MSG_PCS_UDSRESPONSE_BUS 0
#define MSG_PMS_ALERTMATRIX1_ID 900
#define MSG_PMS_ALERTMATRIX1_BUS 0
#define MSG_PMS_INFO_ID 1748
#define MSG_PMS_INFO_BUS 0
#define MSG_PMS_UDSRESPONSE_ID 1620
#define MSG_PMS_UDSRESPONSE_BUS 0
#define MSG_PM_ALERTMATRIX1_ID 772
#define MSG_PM_ALERTMATRIX1_BUS 0
#define MSG_PM_INFO_ID 790
#define MSG_PM_INFO_BUS 0
#define MSG_PM_UDSRESPONSE_ID 1556
#define MSG_PM_UDSRESPONSE_BUS 0
#define MSG_PTC_INFO_ID 837
#define MSG_PTC_INFO_BUS 0
#define MSG_PTC_SENSORSTATUS_ID 647
#define MSG_PTC_SENSORSTATUS_BUS 0
#define MSG_PTC_UDSRESPONSE_ID 1750
#define MSG_PTC_UDSRESPONSE_BUS 0
#define MSG_RADC_ALERTMATRIX0_ID 1282
#define MSG_RADC_ALERTMATRIX0_BUS 1
#define MSG_RADC_INFO_ID 1329
#define MSG_RADC_INFO_BUS 1
#define MSG_RADC_UDSRESPONSE_ID 1665
#define MSG_RADC_UDSRESPONSE_BUS 0
#define MSG_RCM_ALERTMATRIX_ID 881
#define MSG_RCM_ALERTMATRIX_BUS 0
#define MSG_RCM_COLLISION_ID 17
#define MSG_RCM_COLLISION_BUS 0
#define MSG_RCM_INERTIAL1_ID 257
#define MSG_RCM_INERTIAL1_BUS 1
#define MSG_RCM_INERTIAL2_ID 273
#define MSG_RCM_INERTIAL2_BUS 1
#define MSG_RCM_INFO_ID 849
#define MSG_RCM_INFO_BUS 1
#define MSG_RCM_NEARDEPLOY_ID 289
#define MSG_RCM_NEARDEPLOY_BUS 0
#define MSG_RCM_STATUS_ID 529
#define MSG_RCM_STATUS_BUS 0
#define MSG_RCM_UDSRESPONSE_ID 1617
#define MSG_RCM_UDSRESPONSE_BUS 0
#define MSG_SCCM_ALERTMATRIX_ID 1359
#define MSG_SCCM_ALERTMATRIX_BUS 0
#define MSG_SCCM_INFO_ID 816
#define MSG_SCCM_INFO_BUS 0
#define MSG_SCCM_RIGHTSTALK_ID 553
#define MSG_SCCM_RIGHTSTALK_BUS 0
#define MSG_SCCM_LEFTSTALK_ID 585
#define MSG_SCCM_LEFTSTALK_BUS 0
#define MSG_SCCM_STEERINGANGLESENSOR_ID 297
#define MSG_SCCM_STEERINGANGLESENSOR_BUS 0
#define MSG_SCCM_UDSRESPONSE_ID 1680
#define MSG_SCCM_UDSRESPONSE_BUS 0
#define MSG_SCM_ALERTMATRIX1_ID 815
#define MSG_SCM_ALERTMATRIX1_BUS 1
#define MSG_SCM_ALERTMATRIX2_ID 1355
#define MSG_SCM_ALERTMATRIX2_BUS 0
#define MSG_SCS_ALERTMATRIX1_ID 869
#define MSG_SCS_ALERTMATRIX1_BUS 0
#define MSG_SCS_ALERTMATRIX2_ID 880
#define MSG_SCS_ALERTMATRIX2_BUS 1
#define MSG_TAS_HEIGHTS_ID 523
#define MSG_TAS_HEIGHTS_BUS 0
#define MSG_TAS_INFO_ID 1357
#define MSG_TAS_INFO_BUS 0
#define MSG_TAS_STATES_ID 525
#define MSG_TAS_STATES_BUS 0
#define MSG_TAS_UDSRESPONSE_ID 1627
#define MSG_TAS_UDSRESPONSE_BUS 0
#define MSG_TAS_WARNINGMATRIX1_ID 845
#define MSG_TAS_WARNINGMATRIX1_BUS 0
#define MSG_TAS_WARNINGMATRIX2_ID 877
#define MSG_TAS_WARNINGMATRIX2_BUS 0
#define MSG_TAS_WARNINGMATRIX3_ID 909
#define MSG_TAS_WARNINGMATRIX3_BUS 0
#define MSG_TAS_WARNINGMATRIX4_ID 941
#define MSG_TAS_WARNINGMATRIX4_BUS 0
#define MSG_TAS_WARNINGMATRIX5_ID 973
#define MSG_TAS_WARNINGMATRIX5_BUS 0
#define MSG_TPMS_STATUSC_ID 879
#define MSG_TPMS_STATUSC_BUS 1
#define MSG_TPMS_DATA_ID 799
#define MSG_TPMS_DATA_BUS 1
#define MSG_TPMS_INFO_ID 1519
#define MSG_TPMS_INFO_BUS 1
#define MSG_TPMS_UDSRESPONSE_ID 1631
#define MSG_TPMS_UDSRESPONSE_BUS 0
#define MSG_UDS_KOSTIASCCMREQUEST_ID 1641
#define MSG_UDS_KOSTIASCCMREQUEST_BUS 0
#define MSG_UDS_BMSREQUEST_ID 1538
#define MSG_UDS_BMSREQUEST_BUS 0
#define MSG_UDS_CCREQUEST_ID 1579
#define MSG_UDS_CCREQUEST_BUS 0
#define MSG_UDS_CMPREQUEST_ID 1539
#define MSG_UDS_CMPREQUEST_BUS 0
#define MSG_UDS_CPREQUEST_ID 1550
#define MSG_UDS_CPREQUEST_BUS 0
#define MSG_UDS_DASREQUEST_ID 1609
#define MSG_UDS_DASREQUEST_BUS 0
#define MSG_UDS_DIREQUEST_ID 1542
#define MSG_UDS_DIREQUEST_BUS 0
#define MSG_UDS_DISREQUEST_ID 1541
#define MSG_UDS_DISREQUEST_BUS 0
#define MSG_UDS_EPAS3PREQUEST_ID 1584
#define MSG_UDS_EPAS3PREQUEST_BUS 0
#define MSG_UDS_EPAS3SREQUEST_ID 1840
#define MSG_UDS_EPAS3SREQUEST_BUS 0
#define MSG_UDS_EPBLREQUEST_ID 1572
#define MSG_UDS_EPBLREQUEST_BUS 0
#define MSG_UDS_EPBRREQUEST_ID 1574
#define MSG_UDS_EPBRREQUEST_BUS 0
#define MSG_UDS_ESPREQUEST_ID 1605
#define MSG_UDS_ESPREQUEST_BUS 0
#define MSG_UDS_FUNCTIONALREQUEST_ID 2015
#define MSG_UDS_FUNCTIONALREQUEST_BUS 0
#define MSG_UDS_HVPREQUEST_ID 1552
#define MSG_UDS_HVPREQUEST_BUS 0
#define MSG_UDS_IBSTREQUEST_ID 1613
#define MSG_UDS_IBSTREQUEST_BUS 0
#define MSG_UDS_OCS1PREQUEST_ID 1603
#define MSG_UDS_OCS1PREQUEST_BUS 0
#define MSG_UDS_PARKREQUEST_ID 1614
#define MSG_UDS_PARKREQUEST_BUS 0
#define MSG_UDS_PCSREQUEST_ID 1576
#define MSG_UDS_PCSREQUEST_BUS 0
#define MSG_UDS_PMREQUEST_ID 1540
#define MSG_UDS_PMREQUEST_BUS 0
#define MSG_UDS_PMSREQUEST_ID 1604
#define MSG_UDS_PMSREQUEST_BUS 0
#define MSG_UDS_PTCREQUEST_ID 1734
#define MSG_UDS_PTCREQUEST_BUS 0
#define MSG_UDS_RADCREQUEST_ID 1649
#define MSG_UDS_RADCREQUEST_BUS 0
#define MSG_UDS_RCMREQUEST_ID 1601
#define MSG_UDS_RCMREQUEST_BUS 0
#define MSG_UDS_SCCMREQUEST_ID 1664
#define MSG_UDS_SCCMREQUEST_BUS 0
#define MSG_UDS_TASREQUEST_ID 1611
#define MSG_UDS_TASREQUEST_BUS 0
#define MSG_UDS_THCREQUEST_ID 1551
#define MSG_UDS_THCREQUEST_BUS 0
#define MSG_UDS_TPMSREQUEST_ID 1615
#define MSG_UDS_TPMSREQUEST_BUS 0
#define MSG_UDS_VCFRONTREQUEST_ID 1536
#define MSG_UDS_VCFRONTREQUEST_BUS 0
#define MSG_UDS_VCLEFTREQUEST_ID 1570
#define MSG_UDS_VCLEFTREQUEST_BUS 0
#define MSG_UDS_VCRIGHTREQUEST_ID 1544
#define MSG_UDS_VCRIGHTREQUEST_BUS 0
#define MSG_UDS_VCSECREQUEST_ID 1546
#define MSG_UDS_VCSECREQUEST_BUS 0
#define MSG_UI_ISOTPUDPPIPEVCSEC_ID 1153
#define MSG_UI_ISOTPUDPPIPEVCSEC_BUS 0
#define MSG_UI_AIRBAGCUTOFFSTATUS_ID 979
#define MSG_UI_AIRBAGCUTOFFSTATUS_BUS 0
#define MSG_UI_ALERTLOG_ID 1523
#define MSG_UI_ALERTLOG_BUS 0
#define MSG_UI_ALERTMATRIX1_ID 291
#define MSG_UI_ALERTMATRIX1_BUS 0
#define MSG_UI_AUTOPILOTCONTROL_ID 1021
#define MSG_UI_AUTOPILOTCONTROL_BUS 1
#define MSG_UI_CHARGEREQUEST_ID 819
#define MSG_UI_CHARGEREQUEST_BUS 0
#define MSG_UI_CHASSISCONTROL_ID 659
#define MSG_UI_CHASSISCONTROL_BUS 0
#define MSG_UI_CRUISECONTROL_ID 531
#define MSG_UI_CRUISECONTROL_BUS 0
#define MSG_UI_CSAOFFRAMPCURVATURE_ID 664
#define MSG_UI_CSAOFFRAMPCURVATURE_BUS 0
#define MSG_UI_CSAROADCURVATURE_ID 679
#define MSG_UI_CSAROADCURVATURE_BUS 0
#define MSG_UI_DEBUGECU_ID 1280
#define MSG_UI_DEBUGECU_BUS 0
#define MSG_UI_DRIVERASSISTANONDEBUGPARAMS_ID 1096
#define MSG_UI_DRIVERASSISTANONDEBUGPARAMS_BUS 0
#define MSG_UI_DRIVERASSISTCONTROL_ID 1016
#define MSG_UI_DRIVERASSISTCONTROL_BUS 1
#define MSG_UI_DRIVERASSISTMAPDATA_ID 568
#define MSG_UI_DRIVERASSISTMAPDATA_BUS 1
#define MSG_UI_DRIVERASSISTROADSIGN_ID 536
#define MSG_UI_DRIVERASSISTROADSIGN_BUS 0
#define MSG_UI_DRIVERPROFILERECALL_ID 645
#define MSG_UI_DRIVERPROFILERECALL_BUS 0
#define MSG_UI_ELEVATIONSTATUS_ID 984
#define MSG_UI_ELEVATIONSTATUS_BUS 0
#define MSG_UI_VEHNM_ID 1139
#define MSG_UI_VEHNM_BUS 0
#define MSG_UI_GPSVEHICLESPEED_ID 985
#define MSG_UI_GPSVEHICLESPEED_BUS 0
#define MSG_UI_HVACREQUEST_ID 755
#define MSG_UI_HVACREQUEST_BUS 0
#define MSG_UI_LOCATIONSTATUS_ID 79
#define MSG_UI_LOCATIONSTATUS_BUS 1
#define MSG_UI_ODO_ID 1011
#define MSG_UI_ODO_BUS 1
#define MSG_UI_POWERTRAINCONTROL_ID 787
#define MSG_UI_POWERTRAINCONTROL_BUS 0
#define MSG_UI_PRESENTPHONEKEY1INFO_ID 499
#define MSG_UI_PRESENTPHONEKEY1INFO_BUS 0
#define MSG_UI_PRESENTPHONEKEY2INFO_ID 435
#define MSG_UI_PRESENTPHONEKEY2INFO_BUS 0
#define MSG_UI_PRESENTPHONEKEY3INFO_ID 371
#define MSG_UI_PRESENTPHONEKEY3INFO_BUS 0
#define MSG_UI_PRESENTPHONEKEYSOSINFO_ID 307
#define MSG_UI_PRESENTPHONEKEYSOSINFO_BUS 0
#define MSG_UI_RADARMAPDATA_ID 698
#define MSG_UI_RADARMAPDATA_BUS 0
#define MSG_UI_ROADCURVATURE_ID 632
#define MSG_UI_ROADCURVATURE_BUS 0
#define MSG_UI_SOLARDATA_ID 723
#define MSG_UI_SOLARDATA_BUS 0
#define MSG_UI_STATUS_ID 851
#define MSG_UI_STATUS_BUS 0
#define MSG_UI_TELEMETRYCONTROL_ID 1064
#define MSG_UI_TELEMETRYCONTROL_BUS 1
#define MSG_UI_TPMSMODE_ID 856
#define MSG_UI_TPMSMODE_BUS 0
#define MSG_UI_TPMSRCPSETTING_ID 952
#define MSG_UI_TPMSRCPSETTING_BUS 1
#define MSG_UI_VEHICLECONTROL_ID 627
#define MSG_UI_VEHICLECONTROL_BUS 0
#define MSG_UI_VEHICLECONTROL2_ID 947
#define MSG_UI_VEHICLECONTROL2_BUS 0
#define MSG_UI_VEHICLEMODES_ID 644
#define MSG_UI_VEHICLEMODES_BUS 0
#define MSG_UI_VENTPANELCONTROLREQUEST_ID 595
#define MSG_UI_VENTPANELCONTROLREQUEST_BUS 0
#define MSG_UMC_ALERTMATRIX1_ID 824
#define MSG_UMC_ALERTMATRIX1_BUS 0
#define MSG_VCFRONT_12VBATTERYSTATUS_ID 609
#define MSG_VCFRONT_12VBATTERYSTATUS_BUS 0
#define MSG_VCFRONT_LVPOWERSTATE_ID 545
#define MSG_VCFRONT_LVPOWERSTATE_BUS 0
#define MSG_VCFRONT_ALERTMATRIX_ID 832
#define MSG_VCFRONT_ALERTMATRIX_BUS 0
#define MSG_VCFRONT_COOLANT_ID 577
#define MSG_VCFRONT_COOLANT_BUS 0
#define MSG_VCFRONT_EFUSEDEBUGSTATUS_ID 753
#define MSG_VCFRONT_EFUSEDEBUGSTATUS_BUS 0
#define MSG_VCFRONT_INFO_ID 769
#define MSG_VCFRONT_INFO_BUS 0
#define MSG_VCFRONT_LIGHTING_ID 1009
#define MSG_VCFRONT_LIGHTING_BUS 0
#define MSG_VCFRONT_LOGGING10HZ_ID 705
#define MSG_VCFRONT_LOGGING10HZ_BUS 0
#define MSG_VCFRONT_LOGGING1HZ_ID 897
#define MSG_VCFRONT_LOGGING1HZ_BUS 0
#define MSG_VCFRONT_OKTOUSEHIGHPOWER_ID 721
#define MSG_VCFRONT_OKTOUSEHIGHPOWER_BUS 0
#define MSG_VCFRONT_SENSORS_ID 801
#define MSG_VCFRONT_SENSORS_BUS 0
#define MSG_VCFRONT_STATUS_ID 737
#define MSG_VCFRONT_STATUS_BUS 0
#define MSG_VCFRONT_UDSRESPONSE_ID 1537
#define MSG_VCFRONT_UDSRESPONSE_BUS 0
#define MSG_VCFRONT_VEHICLESTATUS_ID 929
#define MSG_VCFRONT_VEHICLESTATUS_BUS 0
#define MSG_VCLEFT_ALERTMATRIX_ID 864
#define MSG_VCLEFT_ALERTMATRIX_BUS 0
#define MSG_VCLEFT_DOORSTATUS_ID 258
#define MSG_VCLEFT_DOORSTATUS_BUS 0
#define MSG_VCLEFT_EPBMDEBUG_ID 626
#define MSG_VCLEFT_EPBMDEBUG_BUS 0
#define MSG_VCLEFT_HVACBLOWERFEEDBACK_ID 642
#define MSG_VCLEFT_HVACBLOWERFEEDBACK_BUS 0
#define MSG_VCLEFT_INFO_ID 770
#define MSG_VCLEFT_INFO_BUS 0
#define MSG_VCLEFT_RECALLSTATUS_ID 1860
#define MSG_VCLEFT_RECALLSTATUS_BUS 0
#define MSG_VCLEFT_RESTRAINTSTATUS_ID 778
#define MSG_VCLEFT_RESTRAINTSTATUS_BUS 0
#define MSG_VCLEFT_SEATSTATUS_ID 1250
#define MSG_VCLEFT_SEATSTATUS_BUS 0
#define MSG_VCLEFT_STATUS_ID 930
#define MSG_VCLEFT_STATUS_BUS 0
#define MSG_VCLEFT_STEERINGCOLUMNSTATUS_ID 610
#define MSG_VCLEFT_STEERINGCOLUMNSTATUS_BUS 0
#define MSG_VCLEFT_SWITCHSTATUS_ID 962
#define MSG_VCLEFT_SWITCHSTATUS_BUS 0
#define MSG_VCLEFT_UDSRESPONSE_ID 1571
#define MSG_VCLEFT_UDSRESPONSE_BUS 0
#define MSG_VCRIGHT_ALERTMATRIX_ID 960
#define MSG_VCRIGHT_ALERTMATRIX_BUS 0
#define MSG_VCRIGHT_DEBUGTHERMAL10HZ_ID 1795
#define MSG_VCRIGHT_DEBUGTHERMAL10HZ_BUS 0
#define MSG_VCRIGHT_DOORSTATUS_ID 259
#define MSG_VCRIGHT_DOORSTATUS_BUS 0
#define MSG_VCRIGHT_EPBMDEBUG_ID 915
#define MSG_VCRIGHT_EPBMDEBUG_BUS 0
#define MSG_VCRIGHT_HVACSTATUS_ID 579
#define MSG_VCRIGHT_HVACSTATUS_BUS 0
#define MSG_VCRIGHT_HVACREQUEST_ID 524
#define MSG_VCRIGHT_HVACREQUEST_BUS 0
#define MSG_VCRIGHT_INFO_ID 774
#define MSG_VCRIGHT_INFO_BUS 0
#define MSG_VCRIGHT_LIGHTSTATUS_ID 995
#define MSG_VCRIGHT_LIGHTSTATUS_BUS 0
#define MSG_VCRIGHT_LOGGING10HZ_ID 611
#define MSG_VCRIGHT_LOGGING10HZ_BUS 0
#define MSG_VCRIGHT_LOGGING1HZ_ID 691
#define MSG_VCRIGHT_LOGGING1HZ_BUS 0
#define MSG_VCRIGHT_RECALLSTATUS_ID 1859
#define MSG_VCRIGHT_RECALLSTATUS_BUS 0
#define MSG_VCRIGHT_RESTRAINTSTATUS_ID 794
#define MSG_VCRIGHT_RESTRAINTSTATUS_BUS 0
#define MSG_VCRIGHT_SEATSTATUS_ID 1251
#define MSG_VCRIGHT_SEATSTATUS_BUS 0
#define MSG_VCRIGHT_THSSTATUS_ID 899
#define MSG_VCRIGHT_THSSTATUS_BUS 0
#define MSG_VCRIGHT_UDSRESPONSE_ID 1545
#define MSG_VCRIGHT_UDSRESPONSE_BUS 0
#define MSG_VCSEC_BLEDEVICESTATUS_ID 857
#define MSG_VCSEC_BLEDEVICESTATUS_BUS 0
#define MSG_VCSEC_BLEENDPOINTINFO_ID 969
#define MSG_VCSEC_BLEENDPOINTINFO_BUS 0
#define MSG_VCSEC_ISOTPPIPEODIN_ID 953
#define MSG_VCSEC_ISOTPPIPEODIN_BUS 0
#define MSG_VCSEC_ISOTPUDPPIPEUI_ID 473
#define MSG_VCSEC_ISOTPUDPPIPEUI_BUS 0
#define MSG_VCSEC_ALERTMATRIX_ID 1017
#define MSG_VCSEC_ALERTMATRIX_BUS 0
#define MSG_VCSEC_AUTHENTICATION_ID 825
#define MSG_VCSEC_AUTHENTICATION_BUS 0
#define MSG_VCSEC_INFO_ID 793
#define MSG_VCSEC_INFO_BUS 0
#define MSG_VCSEC_REQUESTS_ID 505
#define MSG_VCSEC_REQUESTS_BUS 0
#define MSG_VCSEC_UDSRESPONSE_ID 1547
#define MSG_VCSEC_UDSRESPONSE_BUS 0

#define MSG_MULTIPLEX_INFO_SIZE 3
#define MSG_MULTIPLEX_BUS_OFFSET 0
#define MSG_MULTIPLEX_ID_OFFSET 1
#define MSG_MULTIPLEX_COUNT_OFFSET 2
int MSG_MULTIPLEX_INFO[][MSG_MULTIPLEX_INFO_SIZE] = {
  { MSG_VCLEFT_LIFTGATESTATUS_BUS, MSG_VCLEFT_LIFTGATESTATUS_ID, 4 },
  { MSG_VCFRONT_LOGGING10HZ2_BUS, MSG_VCFRONT_LOGGING10HZ2_ID, 8 },
  { MSG_VIN_INFO_BUS, MSG_VIN_INFO_ID, 256 },
  { MSG_BMS_BRICKVOLTAGES_BUS, MSG_BMS_BRICKVOLTAGES_ID, 256 },
  { MSG_APP_CAMCALIBRATIONSTATUS_BUS, MSG_APP_CAMCALIBRATIONSTATUS_ID, 16 },
  { MSG_APP_INFO_BUS, MSG_APP_INFO_ID, 256 },
  { MSG_BMS_ALERTMATRIX_BUS, MSG_BMS_ALERTMATRIX_ID, 16 },
  { MSG_BMS_BMBMINMAX_BUS, MSG_BMS_BMBMINMAX_ID, 4 },
  { MSG_BMS_INFO_BUS, MSG_BMS_INFO_ID, 256 },
  { MSG_BMS_KWHCOUNTERSMULTIPLEXED_BUS, MSG_BMS_KWHCOUNTERSMULTIPLEXED_ID, 8 },
  { MSG_CC_CHGSTATUS2_BUS, MSG_CC_CHGSTATUS2_ID, 256 },
  { MSG_CC_LOGDATA_BUS, MSG_CC_LOGDATA_ID, 256 },
  { MSG_CMP_INFO_BUS, MSG_CMP_INFO_ID, 256 },
  { MSG_CP_ALERTMATRIX_BUS, MSG_CP_ALERTMATRIX_ID, 16 },
  { MSG_CP_INFO_BUS, MSG_CP_INFO_ID, 256 },
  { MSG_CP_SENSORDATA_BUS, MSG_CP_SENSORDATA_ID, 16 },
  { MSG_DAS_INFO_BUS, MSG_DAS_INFO_ID, 256 },
  { MSG_DAS_OBJECT_BUS, MSG_DAS_OBJECT_ID, 8 },
  { MSG_DAS_TELEMETRY_BUS, MSG_DAS_TELEMETRY_ID, 256 },
  { MSG_DAS_TELEMETRYEVENT_BUS, MSG_DAS_TELEMETRYEVENT_ID, 32 },
  { MSG_DAS_TELEMETRYFURNITURE_BUS, MSG_DAS_TELEMETRYFURNITURE_ID, 32 },
  { MSG_DAS_TELEMETRYPERIODIC_BUS, MSG_DAS_TELEMETRYPERIODIC_ID, 32 },
  { MSG_DAS_TELEMETRYRADAR_BUS, MSG_DAS_TELEMETRYRADAR_ID, 32 },
  { MSG_DIS_INFO_BUS, MSG_DIS_INFO_ID, 256 },
  { MSG_DI_DEBUG_BUS, MSG_DI_DEBUG_ID, 256 },
  { MSG_DI_DYNO_BUS, MSG_DI_DYNO_ID, 256 },
  { MSG_DI_INFO_BUS, MSG_DI_INFO_ID, 256 },
  { MSG_EPAS3P_ALERTMATRIX_BUS, MSG_EPAS3P_ALERTMATRIX_ID, 16 },
  { MSG_EPAS3P_INFO_BUS, MSG_EPAS3P_INFO_ID, 256 },
  { MSG_EPAS3S_ALERTMATRIX_BUS, MSG_EPAS3S_ALERTMATRIX_ID, 16 },
  { MSG_EPAS3S_INFO_BUS, MSG_EPAS3S_INFO_ID, 256 },
  { MSG_EPBL_ALERTMATRIX_BUS, MSG_EPBL_ALERTMATRIX_ID, 16 },
  { MSG_EPBL_INFO_BUS, MSG_EPBL_INFO_ID, 256 },
  { MSG_EPBR_ALERTMATRIX_BUS, MSG_EPBR_ALERTMATRIX_ID, 16 },
  { MSG_EPBR_INFO_BUS, MSG_EPBR_INFO_ID, 256 },
  { MSG_ESP_ALERTMATRIX_BUS, MSG_ESP_ALERTMATRIX_ID, 16 },
  { MSG_ESP_INFO_BUS, MSG_ESP_INFO_ID, 256 },
  { MSG_FC_INFO_BUS, MSG_FC_INFO_ID, 256 },
  { MSG_FC_STATUS3_BUS, MSG_FC_STATUS3_ID, 128 },
  { MSG_GTW_ALERTMATRIX_BUS, MSG_GTW_ALERTMATRIX_ID, 16 },
  { MSG_GTW_CARCONFIG_BUS, MSG_GTW_CARCONFIG_ID, 256 },
  { MSG_GTW_HRL_BUS, MSG_GTW_HRL_ID, 4 },
  { MSG_GTW_INFO_BUS, MSG_GTW_INFO_ID, 256 },
  { MSG_HVP_DEBUGMESSAGE_BUS, MSG_HVP_DEBUGMESSAGE_ID, 16 },
  { MSG_HVP_INFO_BUS, MSG_HVP_INFO_ID, 256 },
  { MSG_HVP_VEHICLEDBG_BUS, MSG_HVP_VEHICLEDBG_ID, 32 },
  { MSG_IBST_ALERTMATRIX_BUS, MSG_IBST_ALERTMATRIX_ID, 16 },
  { MSG_IBST_INFO_BUS, MSG_IBST_INFO_ID, 256 },
  { MSG_PARK_INFO_BUS, MSG_PARK_INFO_ID, 256 },
  { MSG_PARK_PSCENVSLOT_BUS, MSG_PARK_PSCENVSLOT_ID, 4 },
  { MSG_PARK_PSCVEHSLOT_BUS, MSG_PARK_PSCVEHSLOT_ID, 4 },
  { MSG_PARK_WARNINGMATRIX_BUS, MSG_PARK_WARNINGMATRIX_ID, 16 },
  { MSG_PCS_ALERTMATRIX_BUS, MSG_PCS_ALERTMATRIX_ID, 16 },
  { MSG_PCS_INFO_BUS, MSG_PCS_INFO_ID, 256 },
  { MSG_PCS_LOGGING_BUS, MSG_PCS_LOGGING_ID, 32 },
  { MSG_PMS_INFO_BUS, MSG_PMS_INFO_ID, 256 },
  { MSG_PM_INFO_BUS, MSG_PM_INFO_ID, 256 },
  { MSG_PTC_INFO_BUS, MSG_PTC_INFO_ID, 256 },
  { MSG_RADC_INFO_BUS, MSG_RADC_INFO_ID, 256 },
  { MSG_RCM_ALERTMATRIX_BUS, MSG_RCM_ALERTMATRIX_ID, 16 },
  { MSG_RCM_INFO_BUS, MSG_RCM_INFO_ID, 256 },
  { MSG_SCCM_ALERTMATRIX_BUS, MSG_SCCM_ALERTMATRIX_ID, 16 },
  { MSG_SCCM_INFO_BUS, MSG_SCCM_INFO_ID, 256 },
  { MSG_TAS_INFO_BUS, MSG_TAS_INFO_ID, 256 },
  { MSG_TPMS_INFO_BUS, MSG_TPMS_INFO_ID, 256 },
  { MSG_UI_ALERTLOG_BUS, MSG_UI_ALERTLOG_ID, 64 },
  { MSG_UI_AUTOPILOTCONTROL_BUS, MSG_UI_AUTOPILOTCONTROL_ID, 8 },
  { MSG_UI_DEBUGECU_BUS, MSG_UI_DEBUGECU_ID, 8 },
  { MSG_UI_DRIVERASSISTROADSIGN_BUS, MSG_UI_DRIVERASSISTROADSIGN_ID, 256 },
  { MSG_UI_DRIVERPROFILERECALL_BUS, MSG_UI_DRIVERPROFILERECALL_ID, 8 },
  { MSG_VCFRONT_LVPOWERSTATE_BUS, MSG_VCFRONT_LVPOWERSTATE_ID, 32 },
  { MSG_VCFRONT_ALERTMATRIX_BUS, MSG_VCFRONT_ALERTMATRIX_ID, 16 },
  { MSG_VCFRONT_EFUSEDEBUGSTATUS_BUS, MSG_VCFRONT_EFUSEDEBUGSTATUS_ID, 32 },
  { MSG_VCFRONT_INFO_BUS, MSG_VCFRONT_INFO_ID, 256 },
  { MSG_VCFRONT_LOGGING10HZ_BUS, MSG_VCFRONT_LOGGING10HZ_ID, 8 },
  { MSG_VCFRONT_LOGGING1HZ_BUS, MSG_VCFRONT_LOGGING1HZ_ID, 32 },
  { MSG_VCFRONT_STATUS_BUS, MSG_VCFRONT_STATUS_ID, 8 },
  { MSG_VCLEFT_ALERTMATRIX_BUS, MSG_VCLEFT_ALERTMATRIX_ID, 16 },
  { MSG_VCLEFT_EPBMDEBUG_BUS, MSG_VCLEFT_EPBMDEBUG_ID, 2 },
  { MSG_VCLEFT_HVACBLOWERFEEDBACK_BUS, MSG_VCLEFT_HVACBLOWERFEEDBACK_ID, 4 },
  { MSG_VCLEFT_INFO_BUS, MSG_VCLEFT_INFO_ID, 256 },
  { MSG_VCLEFT_SEATSTATUS_BUS, MSG_VCLEFT_SEATSTATUS_ID, 8 },
  { MSG_VCLEFT_STATUS_BUS, MSG_VCLEFT_STATUS_ID, 2 },
  { MSG_VCLEFT_SWITCHSTATUS_BUS, MSG_VCLEFT_SWITCHSTATUS_ID, 4 },
  { MSG_VCRIGHT_ALERTMATRIX_BUS, MSG_VCRIGHT_ALERTMATRIX_ID, 16 },
  { MSG_VCRIGHT_DEBUGTHERMAL10HZ_BUS, MSG_VCRIGHT_DEBUGTHERMAL10HZ_ID, 8 },
  { MSG_VCRIGHT_EPBMDEBUG_BUS, MSG_VCRIGHT_EPBMDEBUG_ID, 2 },
  { MSG_VCRIGHT_HVACSTATUS_BUS, MSG_VCRIGHT_HVACSTATUS_ID, 4 },
  { MSG_VCRIGHT_INFO_BUS, MSG_VCRIGHT_INFO_ID, 256 },
  { MSG_VCRIGHT_LOGGING10HZ_BUS, MSG_VCRIGHT_LOGGING10HZ_ID, 8 },
  { MSG_VCRIGHT_LOGGING1HZ_BUS, MSG_VCRIGHT_LOGGING1HZ_ID, 16 },
  { MSG_VCRIGHT_SEATSTATUS_BUS, MSG_VCRIGHT_SEATSTATUS_ID, 8 },
  { MSG_VCSEC_BLEENDPOINTINFO_BUS, MSG_VCSEC_BLEENDPOINTINFO_ID, 8 },
  { MSG_VCSEC_ALERTMATRIX_BUS, MSG_VCSEC_ALERTMATRIX_ID, 16 },
  { MSG_VCSEC_INFO_BUS, MSG_VCSEC_INFO_ID, 256 },
  { -1, -1, -1}
};
